make compile: 
	gcc Main.c -o Main
	gcc binarizacion.c -o binarizacion
	gcc convagris.c -o convagris
	gcc escritura.c -o escritura
	gcc clasificacion.c -o clasificacion
	gcc lectura.c -o lectura
	./Main -c 2 -u 60 -n 88 -b
